#!/usr/bin/with-contenv bash

# install app
[[ ! -d /app/sickrage/.git ]] && \
	git clone -b develop https://github.com/Pymedusa/SickRage.git /app/sickrage

# permissions
chown -R abc:abc \
	/app \
	/config
